[package]
name = "lib_tracer_netdiagnostics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netdiag = {path = "crate/netdiag"}
lazy_static = "1.4.0"
futures     = "0.3.21"

#[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.21", default-features = false }
jni-sys = "0.3.0"


[profile.release]
lto = true


[lib]
name = "tracer_netdiagnostics"
crate-type = ["cdylib"]